version: '3.9'
services:
  client:
    build: client
    ports:
      - "3000:3000"
  admin:
    build: admin
    ports:
      - "4000:4000"
    depends_on:
      - mongodb_container
    environment:
      DATABASE_URL: mongodb://root:rootpassword@mongodb_container:27017/mydb?directConnection=true&authSource=admin   
  tag:
    build: tag
    ports:
      - "4001:4001"
    depends_on:
      - mongodb_container
    environment:
      DATABASE_URL: mongodb://root:rootpassword@mongodb_container:27017/mydb?directConnection=true&authSource=admin
  profile:
    build: profile
    ports:
      - "4002:4002"
    depends_on:
      - mongodb_container
    environment:
      DATABASE_URL: mongodb://root:rootpassword@mongodb_container:27017/mydb?directConnection=true&authSource=admin
  auth:
    build: auth
    ports:
      - "4003:4003"
  analytics:
    build: analytics
    ports:
      - "4004:4004"
  moderator:
    build: moderator
  forgotpw:
    build: forgotpw
    ports:
      - "4006:4006"
    depends_on:
      - mongodb_container
    environment:
      DATABASE_URL: mongodb://root:rootpassword@mongodb_container:27017/mydb?directConnection=true&authSource=admin
  query:
    build: query
    depends_on:
      - mongodb_container
    environment:
      DATABASE_URL: mongodb://root:rootpassword@mongodb_container:27017/mydb?directConnection=true&authSource=admin
  filecompression:
    build: filecompression
    ports:
      - "4008:4008"
    depends_on:
      - mongodb_container
    environment:
      DATABASE_URL: mongodb://root:rootpassword@mongodb_container:27017/mydb?directConnection=true&authSource=admin
  fileservice:
    build: fileservice
    ports:
      - "4009:4009"
  timelogger:
    build: timelogger
    ports:
      - "4010:4010"
  uploaddownload:
    build: uploaddownload
    ports:
      - "4011:4011"
  event-bus:
    build: event-bus
    ports:
      - "4012:4012"
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data_container:/data/db     
volumes:
  mongodb_data_container: